### ISSUE TITLE
Introduction to ExeML: Figure 1 is self linked to the page?

### ISSUE THREAD

**Issue by beibeiJ** [opentelekomcloud-docs/modelarts#10]
Issue on page: https://github.com/opentelekomcloud-docs/modelarts/blob/main/umn/source/exeml/introduction_to_exeml.rst

Should the Figure 1 link to the figure instead of the page? 
![Screenshot 2022-03-25 at 11 40 05](https://user-images.githubusercontent.com/20110950/160106109-5ed0d245-b537-41cf-b112-175df0e142eb.png)

**Comment by kucerakk** [comment]
fixed in latest conversion: 
https://docs-beta.otc.t-systems.com/umn/modelarts/exeml/introduction_to_exeml.html#
