### ISSUE TITLE
Preparing Data: missing hyperlinks 

### ISSUE THREAD

**Issue by beibeiJ** [opentelekomcloud-docs/modelarts#12]
Issue on page: https://github.com/opentelekomcloud-docs/modelarts/blob/main/umn/source/exeml/image_classification/preparing_data.rst

The red lines indicate there should be a hyperlink
![Screenshot 2022-03-25 at 13 04 11](https://user-images.githubusercontent.com/20110950/160118070-f70cb17b-b251-4c1e-9781-fd9bea6cf2a2.png)

**Comment by kucerakk** [comment]
The href entries are missing from the source html.
https://github.com/opentelekomcloud-docs/doc-exports/blob/main/modelarts/umn/modelarts_21_0003.html

It is an issue with the source html file used for conversion and not an issue with the conversion itself.
