### ISSUE TITLE
Preparing Data: content copy and black/white mode

### ISSUE THREAD

**Issue by beibeiJ** [opentelekomcloud-docs/modelarts#13]
Issue on page: https://github.com/opentelekomcloud-docs/modelarts/blob/main/umn/source/exeml/image_classification/preparing_data.rst

**Old HC:**
![Screenshot 2022-03-25 at 13 15 53](https://user-images.githubusercontent.com/20110950/160121190-7daf5df2-7bc2-4e8a-8ddf-da40195a97da.png)

**New HC:**
![Screenshot 2022-03-25 at 13 15 38](https://user-images.githubusercontent.com/20110950/160121221-f6046a7a-0c79-45b2-88d6-53c3d91aabe9.png)

**Comment by gtema** [comment]
Issue https://github.com/opentelekomcloud/otcdocstheme/issues/102 opened for that
