### ISSUE TITLE
Object Detection: item numbering issue

### ISSUE THREAD

**Issue by beibeiJ** [opentelekomcloud-docs/modelarts#16]
Issue on page: https://github.com/opentelekomcloud-docs/modelarts/blob/main/umn/source/data_management/labeling_data/object_detection.rst

In old HC, these two items are 3 and 4.
![Screenshot 2022-03-28 at 16 40 57](https://user-images.githubusercontent.com/20110950/160423466-4ff6f0d3-adf7-4fe3-9ea6-e3e305eea3ba.png)

**Comment by kucerakk** [comment]
In the latest export https://docs-beta.otc.t-systems.com/umn/modelarts/data_management/labeling_data/object_detection.html

These items are marked now 3. and 4. (same as old HC)

![image](https://user-images.githubusercontent.com/8899650/164169432-f60e6701-df2e-438c-a86d-2abf147782f5.png)
