### ISSUE TITLE
XGBoost: two code chunks have different layouts

### ISSUE THREAD

**Issue by beibeiJ** [opentelekomcloud-docs/modelarts#18]
Issue on page: https://github.com/opentelekomcloud-docs/modelarts/blob/main/umn/source/examples_of_custom_scripts/xgboost.rst

The first code chunk has line number but the second code chunk does not have.

**Comment by kucerakk** [comment]
This inconsistency comes from the source html file used for the export and the issue is not related to the conversion itself.

https://github.com/opentelekomcloud-docs/doc-exports/blob/main/modelarts/umn/modelarts_23_0177.html
