### ISSUE TITLE
Deploying a Model as a Service

### ISSUE THREAD

**Issue by beibeiJ** [opentelekomcloud-docs/modelarts#42]
Issue on page: https://github.com/opentelekomcloud-docs/modelarts/blob/main/umn/source/exeml/predictive_analytics/deploying_a_model_as_a_service.rst
![Screenshot 2022-07-18 at 16 17 04](https://user-images.githubusercontent.com/20110950/179531688-6cfae2a0-c1bd-471d-af1a-349aecaa96c5.png)

Hi @gtema you mentioned earlier that if our vendor delivered the HTML without line index, it would be easier for us to add line index. For ModelArts, we have requested and got the HTML code chunks without any line index. Can we add line index for the code chunks from our side?

**Comment by gtema** [comment]
- it is possible to add line numbers by adding `:lineos:` directive to the particular snippet:
```
.. code-block:: ruby
   :linenos:

   Some more Ruby code.
```
- we can't by default enable line numbering for everything (technically we can, but this is definitely not what we want)
- maybe once we split repos to internal and official we can apply those changes. But in any way you need to explicitly decide where you want them and where not (and how to differentiate those things)
