### ISSUE TITLE
Model Deployment grammar issue

### ISSUE THREAD

**Issue by beibeiJ** [opentelekomcloud-docs/modelarts#6]
Issue on page: https://github.com/opentelekomcloud-docs/modelarts/blob/main/umn/source/service_overview/basic_knowledge/model_deployment.rst

“The real-time inference service features high concurrency, low latency, and elastic scaling.” grammar issue?

**Comment by kucerakk** [comment]
The content is coming from the source html:
https://github.com/opentelekomcloud-docs/doc-exports/blob/main/modelarts/umn/modelarts_01_0015.html

It is an issue with the source html file used for conversion and not an issue with the conversion itself.
