### ISSUE TITLE
Related Services: hyperlinks do not show and link to the right webpages

### ISSUE THREAD

**Issue by beibeiJ** [opentelekomcloud-docs/modelarts#7]
Issue on page: https://github.com/opentelekomcloud-docs/modelarts/blob/main/umn/source/service_overview/related_services.rst

Help Center 3.0
![Screenshot 2022-03-23 at 17 12 51](https://user-images.githubusercontent.com/20110950/159745439-e6091152-c1c6-4714-921a-1e2f1d2530d1.png)

Old Help Center

![Screenshot 2022-03-23 at 17 13 39](https://user-images.githubusercontent.com/20110950/159745590-8327c016-ca60-4c09-8169-21ca23b1be6c.png)

**Comment by gtema** [comment]
delivered content was already deviating from current help center. Please clarify that on your side

**Comment by beibeiJ** [comment]
Hi @gtema do you mean the initial HTML file should contain the link first then it will solve the issue?

**Comment by gtema** [comment]
I mean we have received content in this particular way. When there are issues in the export we get there are 2 ways to solve the issue:
- update it in the initial source (what helps further maintenance)
- update here in place as a followup (unties from R&D and makes updates easy, but add deviations which need to be tracked). This is, however, the preferred way
