### ISSUE TITLE
Creating an OBS Bucket: hyperlinks are missing

### ISSUE THREAD

**Issue by beibeiJ** [opentelekomcloud-docs/modelarts#9]
Issue on page: https://github.com/opentelekomcloud-docs/modelarts/blob/main/umn/source/preparations/creating_an_obs_bucket.rst

Hyperlinks (marked blue) are missing:
![Screenshot 2022-03-25 at 11 00 11](https://user-images.githubusercontent.com/20110950/160099322-be1ac705-347d-4fab-b334-505635ee2c03.png)

**Comment by kucerakk** [comment]
The href entries are missing from the source html.
https://github.com/opentelekomcloud-docs/doc-exports/blob/main/modelarts/umn/modelarts_08_0003.html

It is an issue with the source html file used for conversion and not an issue with the conversion itself.
